stages:
  - build
  - test
  - package

image: maven:3.9.6-amazoncorretto-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

build:
  stage: build
  tags:
    - docker
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 2 days
  cache:
    paths:
        - ".m2/repository"

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn test
  cache:
    paths:
      - ".m2/repository"

package:
  stage: package
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn package
  artifacts:
    paths:
      - "target/*.war"
    expire_in: 2 days
  cache:
    paths:
      - ".m2/repository"