stages:
  - build
  - test
  - package
  - deploy

image: maven:3.9.6-amazoncorretto-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

build:
  stage: build
  tags:
    - docker
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 2 days
  cache:
    paths:
        - ".m2/repository"

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn test
  cache:
    paths:
      - ".m2/repository"

package:
  stage: package
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn package
  artifacts:
    paths:
      - "target/*.war"
    expire_in: 2 days
  cache:
    paths:
      - ".m2/repository"

deploy_test:
  stage: deploy
  tags:
    - shell
  dependencies:
    - package
  #when: manual # this job will be executed manually (e.g. button click after payment received)
  script:
    - docker rm --force tomcat # remove the container (tomcat)
    - docker image rm --force connect-four # remove the image
    - docker build -t connect-four . # build the image
    - docker run --rm -d --name tomcat -p 8080:8080 connect-four
  environment:
    name: test
    action: start
    url: http://localhost:8080/ConnectFour
    on_stop: deploy_test_stop

deploy_test_stop:
  stage: deploy
  tags:
    - shell
  when: manual # this job will be executed manually (e.g. button click after payment received)
  script:
    - docker rm --force tomcat # remove the container (tomcat)
    - docker image rm --force connect-four # remove the image
  environment:
    name: test
    action: stop
