name: SPW4 GitHub Actions Pipeline
on: [push]

env:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
#    container:
#      image: maven:3.9.7-eclipse-temurin-21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          # cache: maven? TODO notwendig?
      - run: mvn compile
      # TODO add actions/upload-artifact@v4 ?
      #- uses: actions/cache@v2 TODO Notwendig?
      #  with:
      #    path: ~/.m2/repository
      #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #    restore-keys: ${{ runner.os }}-m2

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
#    container:
#      image: maven:3.9.7-eclipse-temurin-21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          # cache: maven? TODO notwendig?
#      - uses: actions/cache@v2 TODO Notwendig?
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
      - run: mvn test

#      - name: Archive test reports
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-reports
#          path: |
#            target/surefire-reports/*
#            target/site/jacoco/*

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [build, test]
#    container:
#      image: maven:3.9.7-eclipse-temurin-21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          # cache: maven? TODO notwendig?

#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2

      - run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts-${{github.ref_name}}-${{github.sha}}
          path: target/*.war
          retention-days: 1

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: package
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packaged-artifacts-${{github.ref_name}}-${{github.sha}}
          path: target
      - run: cp -f target/ConnectFour.war /usr/local/tomcat/webapps/