name: SPW4 GitHub Actions Pipeline
on: [push]

env:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: mvn compile
      - uses: actions/cache@v4
        with:
          path: .m2/repository
          key: builded-artifacts-${{github.ref_name}}-${{github.sha}}
          restore-keys: builded-artifacts-${{github.ref_name}}-

      - uses: actions/upload-artifact@v4
        with:
          name: builded-artifacts-${{github.job}}-${{github.ref_name}}-${{github.sha}}
          path: target/*
          retention-days: 3

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: .m2/repository
          key: builded-artifacts-${{github.ref_name}}-${{github.sha}}
          restore-keys: builded-artifacts-${{github.ref_name}}-

      - name: Download Builded Artifacts
        uses: actions/download-artifact@v4
        with:
          name: builded-artifacts-build-${{github.ref_name}}-${{github.sha}}
          path: target

      - run: mvn test

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: .m2/repository
          key: builded-artifacts-${{github.ref_name}}-${{github.sha}}
          restore-keys: builded-artifacts-${{github.ref_name}}-

      - name: Download Builded Artifacts
        uses: actions/download-artifact@v4
        with:
          name: builded-artifacts-build-${{github.ref_name}}-${{github.sha}}
          path: target

      - run: mvn package

      - uses: actions/upload-artifact@v4
        with:
          name: packaged-artifacts-${{github.ref_name}}-${{github.sha}}
          path: target/*.war
          retention-days: 3

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: package
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packaged-artifacts-${{github.ref_name}}-${{github.sha}}
          path: target
      - run: rm -rf /usr/local/tomcat/webapps/ConnectFour.war && cp -f target/ConnectFour.war /usr/local/tomcat/webapps/